float32 vx
float32 vy
float32 vz
float32 wx
float32 wy
float32 wz
float32 jointAngle1
float32 jointAngle2
float32 jointAngle3
float32 jointAngle4
---
float32 joint_vel1
float32 joint_vel2
float32 joint_vel3
float32 joint_vel4
